# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: .5
epsilon_finish: 0.01
epsilon_anneal_time: 100000
mask_before_softmax: False


runner: "episode"

batch_size_run: 8
batch_size: 8
optimizer: "rms"

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "qmix"
